name: Deploy to codekrew.org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/codekrew/public_html &&
            git pull origin main &&
            \cp -rf codecrew/members/mugerwa/. /home/mugerwa/public_html/ &&
            \cp -rf codecrew/members/musimenta/. /home/musiimen/public_html/ &&
            \cp -rf codecrew/members/mutakaala/. /home/mutakaba/public_html/ &&
            \cp -rf codecrew/members/nantongo/. /home/nantongo/public_html/ &&
            \cp -rf codecrew/members/ogwal/. /home/ogwal/public_html/ &&
            \cp -rf codecrew/members/ssebyala/. /home/ssebyala/public_html/ &&
            \cp -rf codecrew/members/ssekanjako/. /home/sekanjak/public_html/ &&
            \cp -rf codecrew/members/tendo/. /home/tendo/public_html/ &&
            chown -R codekrew:codekrew /home/codekrew/public_html
          "
